language: java
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
deploy:
  provider: releases
  file: build/libs/rundeck-puppetenterprise-nodes-plugin-*.jar
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
